sudo: required
dist: trusty
group: deprecated-2017Q4

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify


install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - hugo version
  
script:
  - chmod +x deploy.sh
  - ./deploy.sh